name: GlobalMarket
main: com.survivorserver.globalMarket.Market
authors: [Dasfaust, skirts, GenSecrets]
api-version: 1.16
version: 2.0
commands:
    market:
        description: Market commands
depend: [Vault]